/**
 * PLACEHOLDER CATALOG.
 *
 * Every product below is placeholder content standing in for the real THARROS
 * line: names, prices, copy, specifications and inventory counts are invented
 * for layout and commerce purposes and must be replaced before launch. No
 * product carries photography yet — image slots render as ratio-correct frames
 * until `src` is filled in.
 *
 * This module is the single seam a CMS or database swaps in behind: everything
 * that reads products goes through `lib/catalog/queries.ts`.
 */
import type { Product, Size, Variant } from "./types";

const SKU_PREFIX = "TH";

function sized(
  code: string,
  stock: Partial<Record<Size, number>>,
): Variant[] {
  return (Object.keys(stock) as Size[]).map((size) => ({
    size,
    sku: `${SKU_PREFIX}-${code}-${size}`,
    inventory: stock[size] ?? 0,
  }));
}

function shots(
  code: string,
  name: string,
): Product["images"] {
  return [
    {
      code: `${code}-01`,
      alt: `${name}, front view, laid flat`,
      kind: "front",
      ratio: "portrait",
    },
    {
      code: `${code}-02`,
      alt: `${name}, back view, laid flat`,
      kind: "back",
      ratio: "portrait",
    },
    {
      code: `${code}-03`,
      alt: `${name}, close detail of fabric and construction`,
      kind: "detail",
      ratio: "portrait",
    },
    {
      code: `${code}-04`,
      alt: `Model wearing the ${name}`,
      kind: "model",
      ratio: "portrait",
    },
  ];
}

const CARE = [
  "Machine wash cold, inside out.",
  "Tumble dry low or hang to dry.",
  "Do not bleach. Do not iron directly on print.",
];

export const PRODUCTS: Product[] = [
  {
    id: "core-tee",
    name: "Core Tee",
    slug: "core-tee",
    description: "The foundation piece. Heavyweight cotton, boxy through the body.",
    story:
      "The Core Tee is where the collection starts. Cut wide through the chest and shoulder with a shortened body, it holds its shape instead of draping. The wordmark sits small at the left chest — the point is the silhouette, not the branding.",
    price: 7000,
    category: "t-shirts",
    collections: ["collection-01"],
    colorway: "Washed Black",
    images: shots("CORE-TEE", "Core Tee"),
    variants: sized("CORE-TEE", { XS: 6, S: 14, M: 22, L: 18, XL: 9, XXL: 4 }),
    materials: ["Heavyweight cotton jersey", "Ribbed collar", "Tonal embroidery"],
    fit: ["Boxy fit", "Drops at the shoulder", "True to size"],
    care: CARE,
    featured: true,
    isNew: false,
    release: "released",
    releasedAt: "2026-05-02",
  },
  {
    id: "noise-silence-tee",
    name: "Noise / Silence Tee",
    slug: "noise-silence-tee",
    description: "Full-back graphic. Oversized cut, heavy hand-feel print.",
    story:
      "Two words, front and back, set at scale. NOISE across the chest, SILENCE across the back — the same garment read differently depending on which way you are walking. Printed heavy so the graphic sits on the fabric rather than in it.",
    price: 7500,
    category: "t-shirts",
    collections: ["collection-01"],
    colorway: "Off White",
    images: shots("NS-TEE", "Noise / Silence Tee"),
    variants: sized("NS-TEE", { XS: 0, S: 3, M: 5, L: 2, XL: 6, XXL: 3 }),
    materials: ["Heavyweight cotton jersey", "Screen-printed graphic"],
    fit: ["Oversized fit", "Size down for a regular fit"],
    care: CARE,
    featured: true,
    isNew: true,
    release: "released",
    releasedAt: "2026-07-18",
  },
  {
    id: "blank-statement-tee",
    name: "Blank Statement Tee",
    slug: "blank-statement-tee",
    description: "No graphic. Nothing to explain.",
    story:
      "The counterweight to the graphic pieces. Same pattern as the Core Tee, no print, no visible branding — the label is inside the collar. Built to be worn until it fades.",
    price: 6500,
    category: "t-shirts",
    collections: ["collection-01"],
    colorway: "Bone",
    images: shots("BLANK-TEE", "Blank Statement Tee"),
    variants: sized("BLANK-TEE", { XS: 11, S: 20, M: 26, L: 24, XL: 12, XXL: 7 }),
    materials: ["Heavyweight cotton jersey", "Woven inner label"],
    fit: ["Boxy fit", "True to size"],
    care: CARE,
    featured: false,
    isNew: false,
    release: "released",
    releasedAt: "2026-05-02",
  },
  {
    id: "arc-hoodie",
    name: "Arc Hoodie",
    slug: "arc-hoodie",
    description: "Heavyweight fleece with a double-layer hood.",
    story:
      "Built dense enough to hold structure through the hood and shoulder. The arc graphic runs low across the back, breaking at the side seams. Cuffs and hem are ribbed tight so the body keeps its volume.",
    price: 18000,
    category: "hoodies",
    collections: ["collection-01"],
    colorway: "Black",
    images: shots("ARC-HOOD", "Arc Hoodie"),
    variants: sized("ARC-HOOD", { XS: 4, S: 9, M: 15, L: 13, XL: 8, XXL: 3 }),
    materials: ["Heavyweight brushed-back fleece", "Double-layer hood", "Metal-tipped drawcord"],
    fit: ["Relaxed fit", "Dropped shoulder", "True to size"],
    care: CARE,
    featured: true,
    isNew: false,
    release: "released",
    releasedAt: "2026-05-02",
  },
  {
    id: "negative-space-hoodie",
    name: "Negative Space Hoodie",
    slug: "negative-space-hoodie",
    description: "Tonal print, chest to sleeve. Heavyweight fleece.",
    story:
      "The graphic is cut out rather than applied — the shape reads as absence against the fleece. Same body as the Arc Hoodie with a wider sleeve and a longer hem.",
    price: 18500,
    category: "hoodies",
    collections: ["collection-01"],
    colorway: "Charcoal",
    images: shots("NEG-HOOD", "Negative Space Hoodie"),
    variants: sized("NEG-HOOD", { XS: 0, S: 0, M: 2, L: 1, XL: 0, XXL: 0 }),
    materials: ["Heavyweight brushed-back fleece", "Tonal print"],
    fit: ["Oversized fit", "Extended hem"],
    care: CARE,
    featured: false,
    isNew: true,
    release: "released",
    releasedAt: "2026-07-18",
  },
  {
    id: "field-zip-hoodie",
    name: "Field Zip Hoodie",
    slug: "field-zip-hoodie",
    description: "Full-zip with a storm flap and split kangaroo pocket.",
    story:
      "The layering piece. Full-length zip under a storm flap, pocket split at the centre so it works over a bag strap. Cut long enough to sit under the shell.",
    price: 19500,
    category: "hoodies",
    collections: ["collection-01"],
    colorway: "Slate",
    images: shots("FLD-ZIP", "Field Zip Hoodie"),
    variants: sized("FLD-ZIP", { XS: 5, S: 8, M: 11, L: 10, XL: 6, XXL: 2 }),
    materials: ["Heavyweight brushed-back fleece", "Branded zip pull", "Storm flap"],
    fit: ["Regular fit", "Extended length"],
    care: CARE,
    featured: false,
    isNew: false,
    release: "released",
    releasedAt: "2026-05-02",
  },
  {
    id: "monument-crewneck",
    name: "Monument Crewneck",
    slug: "monument-crewneck",
    description: "Structured crewneck with a raised chest hit.",
    story:
      "A crewneck with weight to it. Raised chest graphic, ribbing carried through the collar, cuff and hem so it holds a clean line under outerwear.",
    price: 15000,
    category: "sweatshirts",
    collections: ["collection-01"],
    colorway: "Bone",
    images: shots("MON-CREW", "Monument Crewneck"),
    variants: sized("MON-CREW", { XS: 7, S: 12, M: 16, L: 14, XL: 7, XXL: 3 }),
    materials: ["Heavyweight loopback cotton", "Raised print", "Ribbed trims"],
    fit: ["Regular fit", "True to size"],
    care: CARE,
    featured: true,
    isNew: false,
    release: "released",
    releasedAt: "2026-05-02",
  },
  {
    id: "grain-crewneck",
    name: "Grain Crewneck",
    slug: "grain-crewneck",
    description: "Washed finish, distressed collar and cuff.",
    story:
      "Garment-washed after construction so the surface breaks up and the trims soften. Every piece finishes slightly differently — that is the point.",
    price: 14500,
    category: "sweatshirts",
    collections: ["collection-01"],
    colorway: "Faded Black",
    images: shots("GRN-CREW", "Grain Crewneck"),
    variants: sized("GRN-CREW", { XS: 3, S: 6, M: 4, L: 5, XL: 2, XXL: 1 }),
    materials: ["Garment-washed loopback cotton", "Distressed trims"],
    fit: ["Relaxed fit", "Shrinkage accounted for in the pattern"],
    care: CARE,
    featured: false,
    isNew: false,
    release: "released",
    releasedAt: "2026-05-02",
  },
  {
    id: "utility-cargo-pant",
    name: "Utility Cargo Pant",
    slug: "utility-cargo-pant",
    description: "Wide leg, articulated knee, six pockets.",
    story:
      "Cut wide from the hip with an articulated knee so the leg stacks properly over a boot. Pockets are placed to carry weight without pulling the silhouette out of shape.",
    price: 19000,
    category: "pants",
    collections: ["collection-01"],
    colorway: "Black",
    images: shots("UTL-CARGO", "Utility Cargo Pant"),
    variants: sized("UTL-CARGO", { XS: 4, S: 10, M: 13, L: 11, XL: 6, XXL: 2 }),
    materials: ["Cotton twill", "Reinforced bar-tacking", "Adjustable hem drawcord"],
    fit: ["Wide leg", "Mid rise", "Stacks over footwear"],
    care: CARE,
    featured: false,
    isNew: false,
    release: "released",
    releasedAt: "2026-05-02",
  },
  {
    id: "stacked-sweatpant",
    name: "Stacked Sweatpant",
    slug: "stacked-sweatpant",
    description: "Heavyweight fleece, tapered from the knee.",
    story:
      "Matched to the Arc Hoodie in weight and colour. Full through the thigh, tapering from the knee so it gathers at the ankle instead of dragging.",
    price: 15000,
    category: "pants",
    collections: ["collection-01"],
    colorway: "Black",
    images: shots("STK-SWEAT", "Stacked Sweatpant"),
    variants: sized("STK-SWEAT", { XS: 6, S: 11, M: 17, L: 15, XL: 8, XXL: 4 }),
    materials: ["Heavyweight brushed-back fleece", "Elasticated waist with drawcord"],
    fit: ["Relaxed through the thigh", "Tapered from the knee"],
    care: CARE,
    featured: false,
    isNew: false,
    release: "released",
    releasedAt: "2026-05-02",
  },
  {
    id: "shell-jacket-01",
    name: "Shell Jacket 01",
    slug: "shell-jacket-01",
    description: "Technical outer layer. Taped seams, storm hood.",
    story:
      "The outermost piece in the collection. Cut oversized to layer over the Arc Hoodie, with a storm hood that holds its shape and a hem that sits below the seat.",
    price: 34000,
    category: "outerwear",
    collections: ["collection-01"],
    colorway: "Black",
    images: shots("SHL-01", "Shell Jacket 01"),
    variants: sized("SHL-01", { XS: 2, S: 5, M: 7, L: 6, XL: 4, XXL: 1 }),
    materials: ["Technical woven shell", "Taped seams", "Two-way zip"],
    fit: ["Oversized fit", "Layers over heavyweight fleece"],
    care: [
      "Machine wash cold on a gentle cycle.",
      "Do not tumble dry. Hang to dry.",
      "Do not iron. Do not dry clean.",
    ],
    featured: true,
    isNew: true,
    release: "released",
    releasedAt: "2026-07-18",
  },
  {
    id: "work-jacket",
    name: "Work Jacket",
    slug: "work-jacket",
    description: "Boxy cotton canvas with a four-pocket front.",
    story:
      "Built on a workwear pattern and squared off through the body. The canvas starts stiff and breaks in with wear, holding the shape of whoever wears it.",
    price: 30000,
    category: "outerwear",
    collections: ["collection-01"],
    colorway: "Faded Black",
    images: shots("WRK-JKT", "Work Jacket"),
    variants: sized("WRK-JKT", { XS: 0, S: 0, M: 0, L: 0, XL: 0, XXL: 0 }),
    materials: ["Cotton canvas", "Corozo buttons", "Four-pocket front"],
    fit: ["Boxy fit", "Squared shoulder"],
    care: CARE,
    featured: false,
    isNew: false,
    release: "released",
    releasedAt: "2026-05-02",
  },
  {
    id: "logo-cap",
    name: "Logo Cap",
    slug: "logo-cap",
    description: "Unstructured six-panel with a low embroidered wordmark.",
    story:
      "Unstructured so it collapses flat and sits low. The wordmark is embroidered small on the front panel and repeated on the back strap.",
    price: 6000,
    category: "accessories",
    collections: ["collection-01"],
    colorway: "Black",
    images: shots("LOGO-CAP", "Logo Cap"),
    variants: sized("LOGO-CAP", { OS: 24 }),
    materials: ["Cotton twill", "Embroidered wordmark", "Adjustable strap"],
    fit: ["One size", "Adjustable"],
    care: ["Spot clean only.", "Do not machine wash."],
    featured: false,
    isNew: false,
    release: "released",
    releasedAt: "2026-05-02",
  },
  {
    id: "canvas-tote",
    name: "Canvas Tote",
    slug: "canvas-tote",
    description: "Heavy canvas carry with a reinforced base.",
    story:
      "Cut from the same canvas as the Work Jacket, with a reinforced base and a strap long enough to wear across the shoulder.",
    price: 6500,
    category: "accessories",
    collections: ["collection-01"],
    colorway: "Bone",
    images: shots("CVS-TOTE", "Canvas Tote"),
    variants: sized("CVS-TOTE", { OS: 3 }),
    materials: ["Heavy cotton canvas", "Reinforced base", "Screen-printed wordmark"],
    fit: ["One size"],
    care: ["Spot clean only."],
    featured: false,
    isNew: false,
    release: "released",
    releasedAt: "2026-05-02",
  },
  {
    id: "ribbed-beanie",
    name: "Ribbed Beanie",
    slug: "ribbed-beanie",
    description: "Fine-gauge rib with a woven label at the cuff.",
    story:
      "Knitted long so it can be worn cuffed short or pulled down. Label sits on the cuff, visible either way.",
    price: 5500,
    category: "accessories",
    collections: ["collection-02"],
    colorway: "Charcoal",
    images: shots("RIB-BEAN", "Ribbed Beanie"),
    variants: sized("RIB-BEAN", { OS: 0 }),
    materials: ["Fine-gauge rib knit", "Woven cuff label"],
    fit: ["One size"],
    care: ["Hand wash cold.", "Dry flat."],
    featured: false,
    isNew: true,
    release: "coming-soon",
    releasedAt: "2026-09-12",
  },
];
